"""Visual QA with Claude vision: flags deformed anatomy, creepy artefacts, off-brief images."""
import base64, io, json, re
from PIL import Image
PROMPT = """You are the quality checker for images used in a documentary explainer video.
The image was generated by an AI image model from this prompt:
"{prompt}"
Reject it (ok=false) if ANY of these are clearly visible: missing/extra/malformed heads, faces, hands, fingers, limbs;
bodies twisted the wrong way (e.g. torso facing one way, knees another); melted or merged people/objects;
creepy or disturbing elements (skulls, distorted faces) that the prompt did not ask for; large garbled fake text;
or the image clearly does not match the prompt. Ignore small background imperfections a viewer would not notice.
Reply with JSON only: {{"ok": true|false, "issue": "short reason or empty"}}"""
def check(cfg, image_path, prompt):
    from .llm import vision
    try: t = vision(cfg, image_path, PROMPT.format(prompt=prompt))
    except Exception as e: return True, f"qa-error: {str(e)[:160]}"
    mm = re.search(r"\{.*\}", t, re.S)
    try: j = json.loads(mm.group(0)); return bool(j.get("ok")), j.get("issue", "")
    except Exception: return True, "qa-unparsed: " + (t or "")[:120].replace("\n", " ")
